[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.733.2"

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"

[publish.categories]
v-rising = ["oakveil-update", "mods", "client"]

[package]
namespace = "DiNaSoR"
name = "EclipsePlus"
versionNumber = "1.3.14"
description = "Client UI for Bloodcraftplus!"
websiteUrl = "https://github.com/DiNaSoR/Bloodcraftplus"
containsNsfwContent = false

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Release/net6.0/EclipsePlus.dll"
target = "/BepInEx/plugins/"
