[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.733.2"
deca-VampireCommandFramework = "0.10.4"

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"

[publish.categories]
v-rising = ["oakveil-update", "mods", "server"]

[package]
namespace = "DiNaSoR"
name = "Bloodcraftplus"
versionNumber = "1.12.19"
description = "Leveling, expertise, legacies, professions, familiars, classes, quests!"
websiteUrl = "https://github.com/DiNaSoR/Bloodcraftplus"
containsNsfwContent = false

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Release/net6.0/Bloodcraftplus.dll"
target = "/BepInEx/plugins/"
